### ISSUE TITLE
How to use nodegui/packer with this?

### ISSUE THREAD

**Issue by tiptronic** [nodegui/vue-nodegui#60]
Caution, noob here:

How would I package the demo using nodegui-packer:  [https://github.com/nodegui/packer](https://github.com/nodegui/packer)?

I am on a Mac and packing the normal `nodegui-starter` works just fine, but I can't find out how to build/pack the `vue-nodegui` demo?

If I run `npx nodegui-packer --pack dist/` it obviously doesn't include `demo`

Running : `npx nodegui-packer --pack demo-dist/` creates an executable, but that obviously does nothing because `dist` is not included.

Do I need to re-structure the demo and put everything under `dist`? Or how is that supposed to work...

Any hint appreciated...

**Comment by mpuz** [comment]
Did You solve? I have problem with Linux Appimage - 
```
/vue-nodegui-starter/deploy/linux/build/sl$ ./Application-x86_64.AppImage 
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module './dist'
Require stack:
- /tmp/.mount_ApplicepqAX0/index.js
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/.mount_ApplicepqAX0/index.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/tmp/.mount_ApplicepqAX0/index.js', 'internal/preload' ]
}

```
